---
- name: check package status
  command: dpkg-query -W "{{ deb_package_name }}"
  register: deb_package_check
  failed_when: deb_package_check.rc > 1
  changed_when: deb_package_check.rc == 1

- name: fetch package
  get_url:
    url: "{{ deb_package_url }}"
    dest: "{{ deb_package_dest }}"
  when: deb_package_check.rc == 1

- name: install package
  become: true
  apt:
    deb: "{{ deb_package_dest }}"
  when: deb_package_check.rc == 1
